# Site settings

title: Harry Shotter's Blog
email: Harry.Shotter@Outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Harry Shotter's development blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.harryshotter.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  harry-shotter

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
plugins:
  - jekyll-feed
